### ISSUE TITLE
SRB nozzle placed wrong when combined with RSS and Principia

### ISSUE THREAD

**Issue by rsparkyc** [Starwaster/ProceduralParts#3] opened 2017-05-03 19:10 UTC
You get a nozzle position that looks like this: http://imgur.com/zE2miKa

**Comment by Starwaster** [comment] 2017-05-07 03:03
Need logs on this and ModuleManager.ConfigCache

**Comment by rsparkyc** [comment] 2017-05-07 03:34
Logs and MM Cache attached [Archive.zip](https://github.com/Starwaster/ProceduralParts/files/981301/Archive.zip)

These logs go from bootup to staging (and crashing) the booster with a command core attached.

**Comment by Starwaster** [comment] 2017-05-09 21:15
Not really seeing a smoking gun in the logs. There are some exceptions being thrown after switching to the Flight scene. Some of them Principia (OnGUI event) and some of them Procedural Parts. If the root part is a Procedural part then switch root to something else and see if the problem still persists. Also see if the problem persists with the new release that I put out. (try both, preferably in that order to aid in gathering data)

If you've been doing anything like compiling your own Principia then try doing something about the error in OnGUI. If you can see where it might be tripping on a null ref then put a check in for that, otherwise just encapsulate the entire thing in a try/endtry to suppress the error

BTW, didn't you notice your resource list smashed in that log? Doesn't look like you have the Community Resource pack properly installed

**Comment by rsparkyc** [comment] 2017-05-10 14:21
Hadn't looked too much into the resources in the log, I was really trying to get a minimum amount of mods installed that would cause it to break.  Honestly, for this, I don't even think i need Community Resource Pack, that was for reproducing the 0 burn time issue.

Also, I haven't been compiling my own principia, and since principia is involved, i'm wondering if it's a mac only issue.  It would be great if some Windows people could reproduce this as well.

**Comment by rsparkyc** [comment] 2017-05-26 20:58
So I added some logging in this commit:
https://github.com/rsparkyc/ProceduralParts/commit/51256c076ee3ae0615dbc62820261a733867e278

It looks like the position object on bellTransform is somehow screwed up.  Interesting thing is I don't see it everytime I load the game, but wanted to put this here for reference.

```
[TEST] Finding model transform for SRBBell
[TEST] Position on InitializeBells
[TEST] position: (0, -1.25, 0)
[TEST] Finding model transform for SRBBell
[TEST] Position on InitializeBells
[TEST] position: (-5745608, 2129757, 1803284)
[TEST] Updating Bell position
[TEST] was: (-5745608, 2129757, 1803284)
[TEST] is: (-5745607, 2129758, 1803284)
```

**Comment by rsparkyc** [comment] 2017-05-27 05:15
It seems moving the part initialization from OnStart to OnStartFinished cleared up any issues i was getting with the position being out of whack.

**Comment by eggrobin** [comment] 2017-06-02 08:26
FYI I am wondering whether mockingbirdnest/Principia#1421 might be related; have you confirmed that this issue is a Principia interaction, i.e., that removing Principia makes the issue go away? If so, the fact that moving things from OnStart to OnStartFinished fixes things might be a clue (though one I have yet to interpret).

**Comment by rsparkyc** [comment] 2017-06-02 13:02
Yes, that bug that @NathanKell opened looks like a very similar issue to this.

**Comment by rsparkyc** [comment] 2017-06-02 16:48
@eggrobin for the record, removing principia makes this issue go away

**Comment by eggrobin** [comment] 2017-06-05 17:13
Conclusion from mockingbirdnest/Principia#1421: this is a Principia issue, and it will be fixed in Cauchy.

**Comment by eggrobin** [comment] 2017-06-05 17:14
@Starwaster, you probably want to close this issue.

**Comment by Starwaster** [comment] 2017-06-05 21:05
On the authority of eggrobin... ISSUE CLOSED!

**Comment by eggrobin** [comment] 2017-07-09 17:39
The egg closeth, and the egg re-openeth. It turns out that while mockingbirdnest/Principia#1421 *was* our fault, a bug with the same symptoms, mockingbirdnest/Principia#1460, reported by @jbengtson (regex), occurs even in the absence of principia (a ship with a procedural SRB will have its nozzle in a strange place if it is loaded from a save in flight, although it will be fine from the pad).

@Starwaster, can you re-open this? :-p

**Comment by Starwaster** [comment] 2017-07-09 19:42
ok you people are fellow modders so you know the drill. I need to be able to reliably reproduce this :) Logs, repro instructions, etc.

It doesn't happen for me and I have a shit ton (metric) of mods so I have no idea why this is happening for people.

**Comment by Starwaster** [comment] 2017-07-09 19:42
oops.

**Comment by jrodrigv** [comment] 2017-07-09 19:53
I can confirm this issue. It usually happens when reloading a saved game. I will provide logs

**Comment by Starwaster** [comment] 2017-07-13 22:41
Still waiting for some more repro info here...

**Comment by jrodrigv** [comment] 2017-07-14 05:24
I will try to send you the info during the weekend

**Comment by Starwaster** [comment] 2018-03-28 18:27
Should be fixed in next update.

**Closed as completed by Starwaster** 2018-03-28 18:27 UTC
