### ISSUE TITLE
Game permanently freezes when reroot attempted on this relatively simple vessel

### ISSUE THREAD

**Issue by Atario** [Starwaster/ProceduralParts#20] opened 2017-09-21 07:53 UTC
Logs and craft file:  [unrerootable.zip](https://github.com/Starwaster/ProceduralParts/files/1320338/unrerootable.zip)

(Other mods needed to load:  KIS & KAS, MechJeb, possibly TweakScale and/or AGX)

Only thing I can think of with this vessel that I haven't done before is PP parts in mirror symmetry.

**Comment by ts826848** [comment] 2017-12-02 17:09
Maybe dupe of #14?

**Comment by Atario** [comment] 2017-12-30 07:17
Played with this a little more, and arrived at this minimalist demo of the problem:

1.  Go to VAB/SPH
1.  New vessel
1.  Place a Procedural Battery
1.  Attach a BZ-52 Radial Attachment Point
1.  Use reroot tool to make the attachment point the root
1.  Game freezes hard.  KSP process must be killed to proceed.

Here's a log of when I did this:  
[output_log.txt](https://github.com/Starwaster/ProceduralParts/files/1594223/output_log.txt)

**Comment by Atario** [comment] 2018-01-04 08:25
I've narrowed it a tiny bit more.  It seems that the lockup happens when the reroot *includes or traverses* a procedural part.  In other words, if there are no PP parts in the vessel tree between (and including) the current root and the reroot target, everything is fine.  But if there are any, the game locks up.

**Comment by Starwaster** [comment] 2018-03-28 18:28
duplicate of #14

**Closed as completed by Starwaster** 2018-03-28 18:28 UTC
