### ISSUE TITLE
Re-rooting procedural parts connected with decouplers hangs KSP

### ISSUE THREAD

**Issue by rsparkyc** [Starwaster/ProceduralParts#14] opened 2017-06-22 05:00 UTC
I'll see if i can put together some logs and better reproduction steps later.

**Comment by ts826848** [comment] 2017-12-02 17:39
I came across this when trying to mate my X-1 lookalike with a B-29-based launcher. I'd  start with the launcher, attach a radial decoupler to the top of the fuselage (which is a proc structural piece), then use the Open -> Merge functionality to place the X-1 onto the decoupler. Then I try to reroot so the X-1 cockpit is the root, then KSP freezes.

The original root is the cockpit of the launcher. The root of the X-1 is originally one of the tanks, since I can't surface attach the X-1 if the cockpit is the root.

I replicated the problem using KSP 1.3.1, MM v2.8.1, and Proc Parts v1.2.12. To reproduce:

1. Start new sandbox save, go to VAB
2. Pick random part
3. Attach radial decoupler (any one works)
4. Attach another random part to radial decoupler (needs to be procedural if part from step 2 isn't)
5. Reroot to new part
6. Freeze

I don't get the freeze if I use a stack decoupler (procedural or stock) instead of a radial decoupler.

[Here](https://www.dropbox.com/sh/c84y96s6yvhrz4x/AAC6zyvfwjC1-pKxADcTkXfna?dl=0) are the logs for a run of KSP, after letting KSP hang for ~5 minutes before killing it. I didn't notice a significant increase in RAM usage during that time.

**Comment by Starwaster** [comment] 2017-12-02 22:05
Ok well the good news is that I have managed to repro using @aw1621107 repro steps.

I put in extra debugging to trace anything that Procedural Parts code might be doing but so far it seems that PP code executes and exits without incident. So far it seems that whatever is happening happens in KSP code and no issues or errors are logged and I'm not any closer to understanding why this is happening.

**Comment by Starwaster** [comment] 2018-03-28 19:14
Resolved in KSP 1.4.x update. (not by me, whatever problem it was seems to have been resolved by Squad)

**Closed as completed by Starwaster** 2018-03-28 19:14 UTC
